### ISSUE TITLE
Loading existing worlds crashes tModLoader

### ISSUE THREAD

**Issue by ghost** [Terratroid/Terraria-Metroidmod_TmodLoader#10]
Loading a pre-existing world crashes tModLoader.

This happens because of `TorizoRoomLocation` loading.

For some reason, changing the loading calls for the `TorizoRoomLocation` from `tag.GetAsInt` to `tag.Get<int>` fixes this issue, and allows the loading of worlds that were created without Metroid Mod installed.

**Comment by ghost** [comment]
Something to note is that the calls that rely on a valid `TorizoRoomLocation` value might produce weird behaviour; I have not tested this.

**Comment by Scooterboot** [comment]
Fixed using the provided suggestion. Doesn't seem like any weird behavior has taken place.
