### ISSUE TITLE
Grappling Beam/Vanilla Hook + Morph Ball issue

### ISSUE THREAD

**Issue by ghost** [Terratroid/Terraria-Metroidmod_TmodLoader#12]
Comment from the forum:
`When I turn into a morph ball while being hooked, the morph ball state bugs out. You cannot mine, you are still normal, but you have the buff. You cannot morph again and you cannot click the buff away. Only a save & exit helps.`

**Comment by ThreeDaybreaker** [comment]
From my own experience the grappling beam itself is fine with morphball, its regular non-metroid grappling hooks that the issue of fake morphs.
