### ISSUE TITLE
Right clicking placed items in MP causes them to disappear

### ISSUE THREAD

**Issue by ghost** [Terratroid/Terraria-Metroidmod_TmodLoader#17]
Comment from the forum:
`So it was stated that enemies and bosses have wonky behaviour in multiplayer but so do items that are placed like Missile expansions and the Chozo statues itself. If you try to break it normally / right-click it you won't even receive the item which was a massive pain when we went to the ruins and got nothing out of it aside from the carpet and sandstorm.`

**Comment by Scooterboot** [comment]
I implemented a fix, but I want this tested more before fully closing.

**Comment by Scooterboot** [comment]
No one has reported this as an issue in a long time, so I'm closing this.
