### ISSUE TITLE
Grappling Beam 'cannonball' bug

### ISSUE THREAD

**Issue by ghost** [Terratroid/Terraria-Metroidmod_TmodLoader#19]
Comment from the forum:
`If you're grappled to a platform hold up and jump you fly off screen and you can't use any items or anything.`

Another comment explains that `UP` should be held down and `Jump` should be spammed.

**Comment by Scooterboot** [comment]
I guess this one is fixed, since Noved said it was fixed for them and no one else has reported this issue after the last update.
