### ISSUE TITLE
Nova Laser Drill distance is not normalized

### ISSUE THREAD

**Issue by ghost** [Terratroid/Terraria-Metroidmod_TmodLoader#23]
It feels like the distance from the player to the MouseWorld position is not normalized, since aiming diagonally from the players' position gives you more range than aiming straight up/right/down/left. 

Don't know if this is something that we want to look into, or if it's intentional?

**Comment by Scooterboot** [comment]
It's based on the vanilla Laser Drill, which does the same thing, so #workingAsIntended

**Comment by ghost** [comment]
Neat, time for closure.
