### ISSUE TITLE
When placed, Hyper Beam will remove most tiles and crash the game when a screenshot is taken.

### ISSUE THREAD

**Issue by AbsoluteSNO** [Terratroid/Terraria-Metroidmod_TmodLoader#26]
As I said, Hyper Beam, when placed, will remove most tiles and crash the game when I take a screenshot. When Hyper Beam is picked back up, the tiles will reappear and the game will function as normal.

**Comment by Scooterboot** [comment]
Fixed for next update. It was a minor oversight.
