### ISSUE TITLE
Jumping somersaults even when standing still.

### ISSUE THREAD

**Issue by DanDragonWolf** [Terratroid/Terraria-Metroidmod_TmodLoader#39]
I built the mod using the files from here, and currently jumping will always activate somersaulting. I believe that before you made all suits enable somersaulting for wall jumps, you could jump without somersaulting while standing still.

**Comment by DanDragonWolf** [comment]
I haven't tried it with just Space Jump Boots yet.

**Comment by Scooterboot** [comment]
Fixed
