### ISSUE TITLE
Chozo Ghost not reappearing

### ISSUE THREAD

**Issue by Novedd** [Terratroid/Terraria-Metroidmod_TmodLoader#8]
After the chozo ghost npc died, when a new one arrived there wasn't one, and it just kept repeating the same message with a different name "Old Bird the Chozo Ghost has arrived!" but they never come. Keep in mind Torizo has been defeated and we just killed Golem, So that might have something to do with it but you never know with stuff like this.
https://cdn.discordapp.com/attachments/661513001182035968/795453943656087552/unknown.png

**Comment by ghost** [comment]
I have implemented a local fix, which I think will solve this issue.

If it's not too much to ask, do you still have the log files related to this issue (located in `Documents/My Games/Terraria/ModLoader/Logs/client.txt`?

**Comment by ghost** [comment]
No need for the log files anymore, PR with the fix is attached. Thanks for the report!

When the PR is merged, this issue will automatically be closed.
